application:
  title: "Aplicação desenvolvida por: AmandaPoreto, AndréMelchior e RichardDallaqua"

spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://root:root@127.0.0.1:27017/db?authSource=admin}

server:
  port: 8081
  servlet:
    context-path: /ponto-ms

