application:
  title: "Aplicação desenvolvida por: AmandaPoreto, AndréMelchior e RichardDallaqua"

spring:
  data:
    mongodb:
      uri: mongodb://ec2-54-175-195-27.compute-1.amazonaws.com:27017/db

server:
  port: 8080
  servlet:
    context-path: /ponto-ms

gateways:
  url: ${REPORT_URL:http://localhost:9090/report-ms}