application:
  title: "Aplicação desenvolvida por: AmandaPoreto, AndréMelchior e RichardDallaqua"

spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://guest:guest@127.0.0.1:27017/db?authSource=admin}

server:
  port: 8080
  servlet:
    context-path: /ponto-ms

gateways:
  url: ${REPORT_URL:http://localhost:9090/report-ms}